### ISSUE TITLE
where's the install?

### ISSUE THREAD

**Issue by JakobNorman** [cyberofficial/GameDVR_Config#2]
i cant install it

**Comment by JakobNorman** [comment]
nevermind found it

**Comment by JakobNorman** [comment]
is it not working, you cause my systems main operating system was 8.1 and I updated it to 10 by force? I have a i7-8700k and an rtx 2060 my shadow play doesn't work so I feel I need to resort to this, and obs runs like shit on my pc

**Comment by cyberofficial** [comment]
> is it not working, you cause my systems main operating system was 8.1 and I updated it to 10 by force? I have a i7-8700k and an rtx 2060 my shadow play doesn't work so I feel I need to resort to this, and obs runs like shit on my pc

Program isn't able to update the windows operating system.
